import type { OAS3Definition, OAS3Options } from "swagger-jsdoc";
import path from 'path'
import { fileURLToPath } from "url";
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const sourceDir = path.resolve(__dirname, "../..")
console.log(sourceDir);

const appFile = path.join(sourceDir, "app.ts")

export const doc = {
    // openapi: '3.0.0',
    info: {
        version: '1.0.0',
        title: 'Hindus R Us',
        description: 'An API documentation generated by swagger-autogen.'
    },
    // host: 'localhost:8080',
    host: 'localhost:3000',
    components: {
        schemas: {
            CreateBodyResponse: {
                message: "User created successfully",
                uid: "4gxbGh65tjWoHnuCNNpSCH4GjKv2"
            },
            IdGenSchema: {
                $email: 'johndoe@gmail.com',
                $password: 'password',
                $returnSecureToken: true
            },
            ErrorResponse2xx: {
                success: true,
                message: "Ok",
                status_code: "200"
            },
            ErrorResponse4xx: {
                success: true,
                message: "Ok",
                status_code: "200"
            },
            ErrorResponse5xx: {
                success: true,
                message: "Ok",
                status_code: "200"
            },
            CreateBodyRequest: {
                $email: 'johndoe@example.com',
                emailVerified: false,
                phoneNumber: '+91 1231231231',
                $displayName: 'John Doe',
                $password: "password",
                $role: {
                    '@enum': ["USER", "ADMIN"]
                }
            },
            CreateContentBody: {
                $file: 'filename.png',
                $title: 'Test Content',
                $description: 'A description written for content creation',
                $language: 'english',
                $type: 'educational',
                hidden: false
            },
            UpdateContentBody: {
                title: 'Test Content',
                description: 'A description written for content creation',
                language: 'english',
                hidden: false
            },
            UpdateImageBody: {
                $file: 'filename.png'
            },
            CreateQuizBody: {
                $contentId: '123',
                $title: 'A Test Quiz',
                $description: 'A test description for the quiz',
                $language: 'english',
                $passingScore: 4,
                $maxAttempts: 5,
                $quizType: 'educational',
                $numberOfQuestions: 5
            },
            CreateQuizQuestions: {
                $title: 'A Test Quiz',
                $description: 'A test description for the quiz',
                $options: {
                    "A": "Option 1",
                    "B": "Option 2",
                    "C": "Option 3",
                    "D": "Option 4",
                },
                $correctOption: 'C',
                $explanation: 'Explain the answer here',
                $questionType: 'educational',
                $quizType: 'educational',
            },
            SubmitQuizBody: {
                $options: [
                    {
                        "questionId": '123',
                        "selectedOption": 'A'
                    }
                ]
            },
            // CreateContentRequest: {
            //     type: "object",
            //     required: ["file", "title", "description", "language"],
            //     properties: {
            //         file: {
            //             type: "string",
            //             format: "binary",
            //             description: "File to upload"
            //         },
            //         title: {
            //             type: "string",
            //             example: "Firebase Guide"
            //         },
            //         description: {
            //             type: "string",
            //             example: "How file uploads work"
            //         },
            //         language: {
            //             type: "string",
            //             example: "english"
            //         },
            //         hidden: {
            //             type: "boolean",
            //             example: false
            //         }
            //     }
            // }
        },
        examples: {
            CreateBodyExample: {
                value: {
                    email: 'johndoe@example.com',
                    emailVerified: 'false',
                    phoneNumber: '+91 1231231231',
                    displayName: 'John Doe',
                    password: "password",
                    role: 'USER'
                }
            }
        },
        securitySchemes: {
            Authorization: {
                type:
                    'http',
                scheme: 'bearer',
                bearerFormat: 'JWT',
            },
            "x-api-key": {
                type: 'apiKey',
                name: 'x-api-key',
                in: 'header'
            }
        }
    },
    servers: [
        { url: 'http://localhost:8080' },
        { url: 'http://localhost:3000' },
        { url: 'https://h-dummy-app-express-app-182702284982.asia-south1.run.app/' },
    ],
    apis: ['../app.ts', '../routes/**/*.ts']
};
export const options: OAS3Options = {
    swaggerDefinition: {
        openapi: '3.0.0',
        info: {
            title: 'H Dummy Api specification',
            description: 'API documentation created using swagger-jsdoc',
            version: '1.1.0',
        },
        components: {
            securitySchemes: {
                Authorization: {
                    type: 'http',
                    scheme: 'bearer',
                    bearerFormat: 'JWT',
                },
                "x-api-key": {
                    type: 'apiKey',
                    in: 'header',
                    name: 'x-api-key',
                },
            },
        },
        servers: [
            {
                url: 'http://localhost:3000',
                description: 'Local host server at port 3000',
            },
            {
                url: 'http://localhost:8080',
                description: 'Local host server at port 8080',
            },
        ],
    },
    apis: [
        path.join(sourceDir, 'routes/**/*.ts'),
    ],
}
