export const doc = {
    info: {
        version: '1.0.0',
        title: 'Hindus R Us',
        description: 'An API documentation generated by swagger-autogen.'
    },
    host: 'localhost:3000',
    components: {
        schemas: {
            ErrorResponse2xx: {
                success: true,
                message: "Ok",
                status_code: "200"
            },
            ErrorResponse4xx: {
                success: true,
                message: "Ok",
                status_code: "200"
            },
            ErrorResponse5xx: {
                success: true,
                message: "Ok",
                status_code: "200"
            },
            CreateBodyRequest: {
                $email: 'johndoe@example.com',
                emailVerified: false,
                phoneNumber: '+91 1231231231',
                $displayName: 'John Doe',
                $password: "password",
                $role: {
                    '@enum': ["USER", "ADMIN"]
                }
            },
            CreateContentBody: {
                $file: 'filename.png',
                $title: 'Test Content',
                $description: 'A description written for content creation',
                $language: 'english',
                $type: 'educational',
                hidden: false
            },
            UpdateContentBody: {
                title: 'Test Content',
                description: 'A description written for content creation',
                language: 'english',
                hidden: false
            },
            UpdateImageBody: {
                $file: 'filename.png'
            },
            CreateQuizBody: {
                $contentId: '123',
                $title: 'A Test Quiz',
                $description: 'A test description for the quiz',
                $language: 'english',
                $passingScore: 4,
                $maxAttempts: 5,
                $quizType: 'educational',
                $numberOfQuestions: 5
            },
            CreateQuizQuestions: {
                $title: 'A Test Quiz',
                $description: 'A test description for the quiz',
                $options: {
                    "A": "Option 1",
                    "B": "Option 2",
                    "C": "Option 3",
                    "D": "Option 4",
                },
                $correctOption: 'C',
                $explanation: 'Explain the answer here',
                $questionType: 'educational',
                $quizType: 'educational',
            },
            SubmitQuizBody: {
                $options: [
                    {
                        "questionId": '123',
                        "selectedOption": 'A'
                    }
                ]
            }
            // CreateContentRequest: {
            //     type: "object",
            //     required: ["file", "title", "description", "language"],
            //     properties: {
            //         file: {
            //             type: "string",
            //             format: "binary",
            //             description: "File to upload"
            //         },
            //         title: {
            //             type: "string",
            //             example: "Firebase Guide"
            //         },
            //         description: {
            //             type: "string",
            //             example: "How file uploads work"
            //         },
            //         language: {
            //             type: "string",
            //             example: "english"
            //         },
            //         hidden: {
            //             type: "boolean",
            //             example: false
            //         }
            //     }
            // }
        },
        examples: {
            CreateBodyExample: {
                value: {
                    email: 'johndoe@example.com',
                    emailVerified: 'false',
                    phoneNumber: '+91 1231231231',
                    displayName: 'John Doe',
                    password: "password",
                    role: 'USER'
                }
            }
        },
        securitySchemes: {
            bearerAuth: {
                type: 'http',
                scheme: 'bearer',
                bearerFormat: 'JWT',
            }
        }
    },

    servers: [{ url: 'http://localhost:3000' }],
};
